"""End-to-end checks against the local production preview, using installed Edge."""
import json
import time
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'artifacts'
OUT.mkdir(exist_ok=True)
checks = []
errors = []
def check(name, value):
    checks.append({'check':name,'passed':bool(value)})
    assert value, name

with sync_playwright() as p:
    browser = p.chromium.launch(channel='msedge', headless=True)
    context = browser.new_context(viewport={'width':1440,'height':960},device_scale_factor=1)
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    started = time.perf_counter()
    page.goto('http://127.0.0.1:4173',wait_until='networkidle')
    page.wait_for_function('window.pioneerlab?.getState().world !== null')
    load_seconds = round(time.perf_counter()-started,2)
    page.screenshot(path=str(OUT/'camp-desktop.png'))
    check('3D camp renders',page.locator('#world canvas').count()==1)
    check('Desktop has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    start = page.evaluate('pioneerlab.getState().world.position')
    page.locator('#world canvas').focus()
    page.keyboard.down('w');page.wait_for_timeout(700);page.keyboard.up('w')
    moved = page.evaluate('pioneerlab.getState().world.position')
    check('Keyboard moves the actual avatar',abs(moved['x']-start['x'])+abs(moved['z']-start['z']) > .2)
    page.locator('#first-visit').click()
    page.wait_for_function('pioneerlab.getState().world.nearby === "rope-yard"')
    arrival = page.evaluate('pioneerlab.getState().world.position')
    page.keyboard.press('e')
    check('E opens the nearby rope station',page.locator('#detail-dialog').evaluate('(el)=>el.open'))
    page.locator('#begin-lesson').click()
    page.wait_for_selector('#rope-canvas canvas')
    check('Entering a lesson pauses world movement',page.evaluate('pioneerlab.getState().world.paused'))
    page.keyboard.down('w');page.wait_for_timeout(300);page.keyboard.up('w')
    check('World position is held during lesson',page.evaluate('pioneerlab.getState().world.position')==arrival)
    page.locator('#play-toggle').click();page.wait_for_timeout(400);page.locator('#play-toggle').click()
    paused = page.evaluate('pioneerlab.getState().lesson.time')
    page.wait_for_timeout(250)
    check('Play advances, pause holds the timeline',paused>0 and page.evaluate('pioneerlab.getState().lesson.time')==paused)
    for n in range(1,5):
        page.locator('#next-step').click()
        check(f'Step {n+1} is reachable',page.locator('#instruction .eyebrow').inner_text().startswith(f'STEP {n+1:02}'))
    page.locator('#front-view').click();page.screenshot(path=str(OUT/'lesson-desktop.png'))
    page.locator('#side-view').click();page.screenshot(path=str(OUT/'lesson-side.png'))
    page.locator('#sources-button').click()
    check('Sources can be opened over the lesson',page.locator('#detail-dialog a').count()==3)
    page.keyboard.press('Escape')
    check('Closing sources preserves lesson',page.locator('#lesson-dialog').evaluate('(el)=>el.open'))
    page.locator('#next-step').click()
    page.locator('[data-answer="over"]').click()
    check('Wrong answer gives feedback without completion',page.locator('#quiz-feedback').inner_text()!='' and page.evaluate('pioneerlab.getState().progress.completed.length')==0)
    page.locator('[data-answer="under"]').click()
    check('Correct answer completes the activity',page.evaluate('pioneerlab.getState().progress.completed.includes("clove-hitch")'))
    page.locator('#finish-lesson').click()
    page.wait_for_function('!pioneerlab.getState().world.paused')
    check('Return restores the same camp position',page.evaluate('pioneerlab.getState().world.position')==arrival)
    check('Return resumes movement',not page.evaluate('pioneerlab.getState().world.paused'))
    check('Completion raises the world pennant',page.evaluate('pioneerlab.getState().world.completed'))
    page.reload(wait_until='networkidle')
    check('Activity persists across reload',page.evaluate('pioneerlab.getState().progress.completed.includes("clove-hitch")'))
    check('Old completed lesson now shows one of three activities',page.locator('#progress-count').inner_text()=='1/3')
    page.locator('[data-station="shelter"]').click()
    check('Shelter offers its own complete lesson',page.locator('#begin-lesson').count()==1 and page.locator('#detail-title').inner_text()=='Secure a shelter guyline')
    page.locator('#walk-station').click()
    page.wait_for_function('pioneerlab.getState().world.nearby === "shelter"')
    page.wait_for_timeout(200)
    shelter_arrival=page.evaluate('pioneerlab.getState().world.position')
    page.keyboard.press('e')
    check('Shelter walk-to position remains inside the interaction zone',page.locator('#detail-dialog').evaluate('(el)=>el.open'))
    page.locator('#begin-lesson').click();page.wait_for_selector('#rope-canvas canvas')
    check('Shelter opens a distinct six-step lesson',page.evaluate('pioneerlab.getState().lesson.id')=='round-turn-two-half-hitches' and page.locator('#timeline').get_attribute('max')=='6')
    check('Shelter title and timer match the selected content','Two Half Hitches' in page.locator('#lesson-title').inner_text() and page.locator('#time-label').inner_text().endswith('0:30'))
    page.locator('#play-toggle').click();page.wait_for_timeout(350);page.locator('#play-toggle').click()
    check('Shelter playback advances independently',page.evaluate('pioneerlab.getState().lesson.time')>0)
    page.locator('#sources-button').click()
    check('Shelter uses its own source references',page.locator('a[href="https://www.scouts.org.uk/activities/practice-mooring-a-boat/"]').count()==1)
    page.keyboard.press('Escape')
    for n in range(1,6):
        page.locator('#next-step').click()
        check(f'Shelter step {n+1} is reachable',page.locator('#instruction .eyebrow').inner_text()==f'STEP {n+1:02} / 06')
    page.locator('#front-view').click();page.wait_for_timeout(150);page.screenshot(path=str(OUT/'shelter-lesson-desktop.png'))
    page.locator('#side-view').click();page.wait_for_timeout(150);page.screenshot(path=str(OUT/'shelter-lesson-side.png'))
    page.locator('#next-step').click();page.locator('[data-answer="first-hitch"]').click()
    check('Wrong shelter answer does not award another activity',page.evaluate('pioneerlab.getState().progress.completed.length')==1)
    page.locator('[data-answer="round-turn"]').click()
    check('Shelter completion preserves the rope yard',page.evaluate('pioneerlab.getState().progress.completed')==['clove-hitch','round-turn-two-half-hitches'])
    page.locator('#finish-lesson').click()
    page.wait_for_function('!pioneerlab.getState().world.paused')
    check('Shelter return restores the same location',page.evaluate('pioneerlab.getState().world.position')==shelter_arrival)
    check('Shelter completion reveals its practice guyline',page.evaluate('pioneerlab.getState().world.shelterCompleted'))
    page.screenshot(path=str(OUT/'shelter-completed-camp.png'))
    page.reload(wait_until='networkidle')
    check('Both earlier activities persist across reload',page.locator('#progress-count').inner_text()=='2/3' and page.evaluate('pioneerlab.getState().world.shelterCompleted'))
    check('The next suggested destination is the rack',page.locator('#first-visit').get_attribute('data-destination')=='camp-rack' and 'rack' in page.locator('#first-visit').inner_text())
    page.locator('#progress-button').click()
    check('Journal tracks three lessons separately',page.locator('[data-journal]').count()==3 and page.locator('[data-journal="camp-rack"]').inner_text().find('not yet completed')>=0)
    page.locator('[data-journal="rope-yard"] button').click();page.locator('#begin-lesson').click()
    check('Revisiting Clove Hitch restores its five-step content',page.locator('#timeline').get_attribute('max')=='5' and page.evaluate('pioneerlab.getState().lesson.id')=='clove-hitch')
    page.locator('#return-camp').click()
    page.locator('[data-station="camp-rack"]').click()
    check('Station 3 offers its own lashing lesson',page.locator('#detail-title').inner_text()=='Build a rack joint' and page.locator('#begin-lesson').count()==1)
    page.locator('#walk-station').click();page.wait_for_timeout(200)
    page.wait_for_function('pioneerlab.getState().world.nearby === "camp-rack"')
    rack_arrival=page.evaluate('pioneerlab.getState().world.position')
    page.keyboard.press('e');page.locator('#begin-lesson').click();page.wait_for_selector('#rope-canvas canvas')
    check('Rack opens eight lashing stages',page.evaluate('pioneerlab.getState().lesson.id')=='square-lashing' and page.locator('#timeline').get_attribute('max')=='8')
    check('Rack timeline lasts forty seconds',page.locator('#time-label').inner_text().endswith('0:40'))
    for n in range(1,8):
        page.locator('#next-step').click()
        check(f'Rack stage {n+1} is reachable',page.locator('#instruction .eyebrow').inner_text()==f'STEP {n+1:02} / 08')
    page.locator('#front-view').click();page.wait_for_timeout(150);page.screenshot(path=str(OUT/'rack-lesson-desktop.png'))
    page.locator('#side-view').click();page.wait_for_timeout(150);page.screenshot(path=str(OUT/'rack-lesson-side.png'))
    page.locator('#sources-button').click()
    check('Rack shows its traditional-lashing reference',page.locator('a[href="https://filestore.scouting.org/filestore/Merit_Badge_ReqandRes/Pamphlets/Pioneering.pdf"]').count()==1)
    page.keyboard.press('Escape');page.locator('#next-step').click()
    page.locator('[data-answer="single-pole"]').click()
    check('Wrong rack answer preserves previous progress',page.evaluate('pioneerlab.getState().progress.completed.length')==2)
    page.locator('[data-answer="wrapping-bundle"]').click()
    check('Rack quiz completes the third independent activity',page.evaluate('pioneerlab.getState().progress.completed')==['clove-hitch','round-turn-two-half-hitches','square-lashing'])
    page.locator('#finish-lesson').click();page.wait_for_function('!pioneerlab.getState().world.paused')
    check('Rack return restores the same camp spot',page.evaluate('pioneerlab.getState().world.position')==rack_arrival)
    check('Rack completion reveals its world payoff',page.evaluate('pioneerlab.getState().world.rackCompleted'))
    page.reload(wait_until='networkidle')
    check('All three activities survive reload',page.locator('#progress-count').inner_text()=='3/3' and page.evaluate('pioneerlab.getState().world.rackCompleted'))
    page.locator('#help-button').click();page.locator('#reduced-motion').check();page.keyboard.press('Escape')
    check('Dialogs close with Escape',not page.locator('#detail-dialog').evaluate('(el)=>el.open'))
    check('No JavaScript runtime errors',not errors)
    gpu=page.locator('#world canvas').evaluate('el=>{const gl=el.getContext("webgl2");const x=gl.getExtension("WEBGL_debug_renderer_info");return x?gl.getParameter(x.UNMASKED_RENDERER_WEBGL):"unknown"}')
    fps=page.evaluate('''() => new Promise(resolve=>{let n=0,begin=performance.now();function f(){n++;if(performance.now()-begin>1500)resolve(Math.round(n*1000/(performance.now()-begin)));else requestAnimationFrame(f)}requestAnimationFrame(f)})''')
    # Direct station access must remain usable at phone widths.
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=str(OUT/'camp-mobile.png'))
    check('390px layout has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.locator('[data-station="camp-rack"]').click();page.locator('#begin-lesson').click()
    page.screenshot(path=str(OUT/'rack-lesson-mobile.png'),full_page=True)
    check('Mobile can open and close the lesson directly',page.locator('#return-camp').is_visible())
    page.locator('#return-camp').click()
    page.set_viewport_size({'width':320,'height':720})
    check('320px layout has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    # A saved v1 record from the first release must still work with three lessons.
    migrated=browser.new_context(viewport={'width':1024,'height':700})
    migrated.add_init_script('localStorage.setItem("pioneerlab-camp-v1", JSON.stringify({version:1,discovered:["rope-yard"],completed:["clove-hitch"]}))')
    old_page=migrated.new_page();old_page.goto('http://127.0.0.1:4173',wait_until='networkidle')
    check('Release-one saved progress survives the new version',old_page.locator('#progress-count').inner_text()=='1/3' and old_page.evaluate('pioneerlab.getState().world.completed'))
    migrated.close()
    browser.close()

result={'checks':checks,'passed':sum(c['passed'] for c in checks),'total':len(checks),'errors':errors,'environment':{'browser':'Installed Microsoft Edge, headless','gpu':gpu,'load_seconds_including_network_idle':load_seconds,'sampled_fps':fps,'viewport':'1440x960'},'limitations':['Synthetic browser checks; not tested on physical phones.','Rope path illustration, not a physical tightening simulation or instructor certification.']}
(OUT/'verification.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
print(json.dumps(result,indent=2))
