export const stations = [
  {id:'rope-yard', number:'01', name:'Rope practice yard', task:'Start with a Clove Hitch', category:'YOUR FIRST LESSON', x:-5, z:0, entry:{x:-4,z:3}, description:'A rope, a wooden spar, and a useful place to begin. Follow one continuous rope around the post, then look closely at what holds the hitch together.', detail:'Learn to recognise the two turns and the diagonal tuck. A Clove Hitch is often used to begin a lashing.', duration:'5 steps · 3 min', available:true, lessonId:'clove-hitch'},
  {id:'shelter', number:'02', name:'Shelter corner', task:'Secure a shelter guyline', category:'ANCHORS & ATTACHMENTS', x:5, z:-3, entry:{x:5,z:0}, description:'Trace a guyline from the shelter to its anchor. Learn how a round turn takes the pull, then how two half hitches secure the working end.', detail:'Practise a Round Turn and Two Half Hitches on a model post. This is a fixed tie-off after the line has been positioned; it is not an adjustable guyline hitch.', duration:'6 steps · 4 min', available:true, lessonId:'round-turn-two-half-hitches'},
  {id:'camp-rack', number:'03', name:'Camp rack workshop', task:'Build a rack joint', category:'LASHINGS & CAMP PROJECTS', x:4, z:6, entry:{x:2,z:6}, description:'A rack begins with a reliable joint. Explore how one rope joins an upright pole and a crossbar, then trace the wrapping and frapping turns of a square lashing.', detail:'Study one practice joint with two touching poles at a right angle. The full rack shows where this joint belongs; real construction also needs suitable materials, bracing and qualified guidance.', duration:'8 steps · 5 min', available:true, lessonId:'square-lashing'},
];
const cloveSteps = [
  {short:'Meet the rope', title:'One rope. Two ends.', text:'The standing part is the longer, held section, laid across the front of the spar. The working end is the tip you move. Both belong to the same orange rope.', cue:'The white endpoint marks the working end. The moving bead guides your eye along the route.'},
  {short:'First turn', title:'Go once around the spar.', text:'Take the working end behind the wooden spar and bring it back to the front. Keep the standing part in place.', cue:'Orbit the view to see the rope behind the spar.'},
  {short:'Make the crossing', title:'Cross over the standing part.', text:'Carry the working end diagonally across the front, over the standing part. This creates the crossing that will hold the final tuck.', cue:'The diagonal strand sits on the outside of the crossing.'},
  {short:'Second turn', title:'Go around a second time.', text:'Continue around the spar in the same direction, below the first turn. Keep the two turns separate so you can follow their path.', cue:'There are now two turns around the spar.'},
  {short:'Tuck & inspect', title:'Tuck beneath the diagonal.', text:'Pass the working end underneath the diagonal crossing and let it emerge on the other side. In physical practice, pull the ends to dress the hitch neatly.', cue:'Inspect the tuck from the front, then check from the side.'},
];
const cloveSources = [
  {title:'The Scout Association · A knotty challenge', url:'https://prod-cms.scouts.org.uk/media/2732/a-knotty-challenge-what-knot.pdf'},
  {title:'Scouts · Safe pioneering techniques', url:'https://www.scouts.org.uk/volunteers/staying-safe-and-safeguarding/safety/safe-camping-residentials-and-outdoor-skills/safe-pioneering/technique/'},
  {title:'Scouts · Knot your average pioneer', url:'https://www.scouts.org.uk/activities/knot-your-average-pioneer/'},
];

const shelterSteps = [
  {short:'Follow the guyline',title:'From shelter to anchor.',text:'The standing part leads back to the shelter. The working end goes around the practice post. Both are parts of the same rope.',cue:'The green endpoint marks the line to the shelter. Follow the moving bead along its route.'},
  {short:'Make the round turn',title:'Take two turns around the post.',text:'Bring the working end around the anchor twice in the same direction. These side-by-side wraps form the round turn and help take the pull on the line.',cue:'Use the Side view to inspect both wraps. They should sit beside each other.'},
  {short:'Return to the line',title:'Bring the end back alongside.',text:'After the round turn, bring the working end back beside the standing part. The next two hitches go around that part of the rope, not around the post.',cue:'Follow the line leaving the post toward the two small hitches.'},
  {short:'First turn & crossover',title:'Follow the turn and outer crossing.',text:'Two half hitches form a connected pattern around the standing rope. In this fixed view, trace the first small turn, then the raised strand crossing its front.',cue:'The highlighted strand is the outer crossover. The final tuck appears in the next stage.'},
  {short:'Second turn & tuck',title:'Find the second turn and the tuck.',text:'Continue around the standing rope in the same direction, then trace the end beneath the outer crossover. Together these turns form two same-handed half hitches.',cue:'In physical practice, form each half hitch by passing the end around the standing rope and through its own opening. The bead traces the finished route.'},
  {short:'Dress & check',title:'Check the whole tie-off.',text:'In physical practice, dress the turns neatly and snug the two half hitches together. Inspect the anchor, wraps, crossings, and remaining tail with your instructor.',cue:'This is a fixed tie-off. Its shape alone does not tell you whether a real shelter or anchor is safe.'},
];
const rackSteps = [
  {short:'Start with a hitch',title:'Two poles. One starting hitch.',text:'The upright and crossbar touch at a right angle. Start with a Clove Hitch on the upright, below the crossing. This familiar hitch anchors the lashing rope.',cue:'Trace the starting hitch. In physical practice, secure its short tail around the running part before wrapping.'},
  {short:'First wrapping turn',title:'Follow the first wrap.',text:'Take the working end around both poles. The route passes in front of one pole and behind the other, gathering them into one joint.',cue:'Use the Side view to follow the rope behind the upright.'},
  {short:'Second wrapping turn',title:'Lay the next turn alongside.',text:'Follow the same route again. Keep this turn beside the first so the strands stay orderly and make contact with the poles.',cue:'Wrapping turns run parallel; avoid piling one turn over another.'},
  {short:'Third wrapping turn',title:'Complete the wrapping bundle.',text:'This traditional square-lashing method uses three wrapping turns. In practice, pull each turn tight as you make it.',cue:'Three wraps now join the upright and crossbar. The next turns follow a different route.'},
  {short:'First frapping turn',title:'Go around the wraps.',text:'The frapping turn travels between the poles, around the wrapping bundle. It crosses the direction of the wraps to draw them together.',cue:'A frap surrounds the rope bundle, not just the outside of one pole.'},
  {short:'Second frapping turn',title:'Tighten the bundle again.',text:'Follow a second frapping turn alongside the first. In physical practice, pulling these turns snug reduces movement in the joint.',cue:'The model stays still: the bead shows the route, not a tightening simulation.'},
  {short:'Finish with a hitch',title:'Secure the working end.',text:'Finish this method with a Clove Hitch on the horizontal crossbar. Keep the finishing hitch close to the lashing.',cue:'Find its crossing and the tucked end. Revisit Station 1 to study the Clove Hitch by itself.'},
  {short:'Inspect the rack joint',title:'From a joint to a camp rack.',text:'Check the parallel wraps, the fraps around them, and both hitches. A rack needs sound joints and appropriate bracing throughout, not just one finished lashing.',cue:'Inspect the practice joint with your instructor before using this technique on a real project.'},
];
export const lessons = {
  'clove-hitch': {
    id:'clove-hitch',title:'The Clove Hitch',stationId:'rope-yard',geometry:'clove',steps:cloveSteps,sources:cloveSources,
    referenceIntro:'This introductory path study uses the end-of-rope Clove Hitch method around a spar. It is informed by these Scouting references.',
    footer:'Illustrative rope-path study: playback traces the route, not physical tying or tension. Practise with qualified guidance; this hitch can slip or bind.',
    quiz:{question:'Where does the final tuck go?',prompt:'Look at the front of the spar. The working end passes…',options:[{id:'over',text:'Over the diagonal crossing'},{id:'under',text:'Under the diagonal crossing'},{id:'none',text:'Straight down, without a tuck'}],answer:'under',incorrect:'Look again at the outer diagonal. The working end needs to pass beneath it, between that strand and the spar.'},
    successTitle:'Your first knot, understood.',successText:'That’s it. The working end tucks underneath the diagonal crossing. The two turns and the tuck give this hitch its shape.',payoff:'Your pennant is raised at the rope yard. Try tracing the whole rope again, then practise with qualified guidance.',
  },
  'round-turn-two-half-hitches': {
    id:'round-turn-two-half-hitches',title:'Round Turn & Two Half Hitches',stationId:'shelter',geometry:'shelter',steps:shelterSteps,
    sources:[{title:'Scouts · Practise mooring a boat',url:'https://www.scouts.org.uk/activities/practice-mooring-a-boat/'},{title:'The Scout Association · A knotty challenge',url:'https://prod-cms.scouts.org.uk/media/2732/a-knotty-challenge-what-knot.pdf'},{title:'Scouts · Fly the flag',url:'https://www.scouts.org.uk/activities/fly-the-flag/'}],
    referenceIntro:'This practice-post study shows a Round Turn and Two Half Hitches. Scouting activities use it to attach a line to an anchor and explain that the round turn takes the strain while the half hitches secure it.',
    footer:'Illustrative practice tie-off: playback traces the rope, not tightening or load. Check real anchors, ropes, weather and shelter setup with qualified guidance.',
    quiz:{question:'Which part takes the pull?',prompt:'Before the half hitches secure the end, which part helps take the pull on the line?',options:[{id:'first-hitch',text:'The first half hitch'},{id:'round-turn',text:'The round turn around the anchor'},{id:'tail',text:'The loose rope tail'}],answer:'round-turn',incorrect:'Trace the two wraps around the post. The round turn takes the pull; the two half hitches secure the working end.'},
    successTitle:'A useful tie-off, understood.',successText:'Yes. The round turn takes the pull; the two half hitches keep the end secured. Together they form a fixed tie-off.',payoff:'A highlighted practice guyline now appears at Shelter Corner. You can revisit the lesson from your field journal at any time.',
  },
  'square-lashing': {
    id:'square-lashing',title:'The Square Lashing',stationId:'camp-rack',geometry:'rack',steps:rackSteps,
    sources:[{title:'Scouting America · Pioneering, traditional square lashing (pp. 30–31)',url:'https://filestore.scouting.org/filestore/Merit_Badge_ReqandRes/Pamphlets/Pioneering.pdf'},{title:'Scouts · Scout Adventures lashings guide',url:'https://prod-cms.scouts.org.uk/media/2710/scout-adventures-lashings-guide.pdf'},{title:'Scouts · Pioneering techniques and camp projects',url:'https://www.scouts.org.uk/volunteers/staying-safe-and-safeguarding/safety/safe-camping-residentials-and-outdoor-skills/safe-pioneering/technique/'}],
    referenceIntro:'This study follows the traditional square-lashing method in Scouting America’s Pioneering booklet: a starting Clove Hitch, three wraps, two fraps, and a finishing Clove Hitch. Other taught methods may use different counts or finishes.',
    footer:'Illustrative rack joint: playback traces the rope, not tightening or structural strength. Practise with qualified guidance before building or loading a real rack.',
    quiz:{question:'What do the frapping turns tighten?',prompt:'Look between the two poles. The frapping turns pass around…',options:[{id:'single-pole',text:'Just the outside of one pole'},{id:'wrapping-bundle',text:'The bundle of wrapping turns'},{id:'loose-tail',text:'Only the loose starting tail'}],answer:'wrapping-bundle',incorrect:'Follow the turns between the poles. They surround the wrapping bundle and draw it together; the earlier wraps go around the poles.'},
    successTitle:'A camp joint, understood.',successText:'Yes. The frapping turns tighten the wrapping bundle. Together with the starting and finishing hitches, they complete this square-lashing pattern.',payoff:'Highlighted joints and a rolled camp mat now appear on your rack. Your field journal keeps this activity alongside the two earlier lessons.',
  },
};
export const lessonIds = Object.keys(lessons);
